version: '3'

services:
  postgres-container:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: makifore
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: book_shelf
