name: "Setup Repository"

runs:
  using: "composite"

  steps:
    - name: Setup node
      uses: actions/setup-node@3
      with:
        node-version: 18

    - name: Put node version
      shell: bash
      run: echo "The version of Node.js used is $(node -v)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --strict-peer-dependencies --prefer-offline
      env:
        HUSKY: "0"
