import type { AppProps } from 'next/app';

import Head from 'next/head';
import Router from 'next/router';

import { ThemeProvider } from '@mui/material';

import nProgress from 'nprogress';

import { SnackbarProvider } from '@/components/contexts/SnackbarContext';
import Box from '@/components/mui/Box';
import AppHeader from '@/components/organisms/AppHeader';

import theme from '@/styles/theme';
import 'nprogress/nprogress.css';

Router.events.on('routeChangeStart', () => nProgress.start());
Router.events.on('routeChangeError', () => nProgress.done());
Router.events.on('routeChangeComplete', () => nProgress.done());

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Book Shelf</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <ThemeProvider theme={theme}>
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'gray.background',
            width: '100%',
            height: '100%',
            px: 4,
          }}
        >
          <SnackbarProvider>
            <Box>
              <AppHeader />
              <Box sx={{ pt: '56px' }}>
                <Component {...pageProps} />
              </Box>
            </Box>
          </SnackbarProvider>
        </Box>
      </ThemeProvider>
    </>
  );
}
