import type { AppProps } from 'next/app';

import Head from 'next/head';
import Router, { useRouter } from 'next/router';

import { ThemeProvider } from '@mui/material';

import nProgress from 'nprogress';

import { SnackbarProvider } from '@/components/contexts/SnackbarContext';
import Box from '@/components/mui/Box';
import AppHeader from '@/components/organisms/AppHeader';

import theme from '@/styles/theme';

import 'nprogress/nprogress.css';

Router.events.on('routeChangeStart', () => nProgress.start());
Router.events.on('routeChangeError', () => nProgress.done());
Router.events.on('routeChangeComplete', () => nProgress.done());

const App = ({ Component, pageProps }: AppProps) => {
  const router = useRouter();

  const removeHeaderPath = ['/signup', '/signin', '/register', '/403', '/404', '500'] as const;

  return (
    <>
      <Head>
        <title>Book Shelf</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <ThemeProvider theme={theme}>
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'gray.background',
            width: '100%',
            height: '100%',
            px: 4,
          }}
        >
          <SnackbarProvider>
            {removeHeaderPath.some((path) => path === router.pathname) ? (
              <Component {...pageProps} />
            ) : (
              <>
                <AppHeader />
                <Box sx={{ pt: '56px' }}>
                  <Component {...pageProps} />
                </Box>
              </>
            )}
          </SnackbarProvider>
        </Box>
      </ThemeProvider>
    </>
  );
};

export default App;
