import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Box from '@/components/mui/Box';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Box
        sx={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: '#f0f3fd',
          width: '100%',
          height: '100%',
          px: 4,
        }}
      >
        <Component {...pageProps} />
      </Box>
    </>
  );
}
