name: 'Run CI'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: 'read'

jobs:
  run_build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: book_shelf
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/book_shelf
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: prisma migrate
        uses: './.github/workflows/excute_pnpm_command.yaml'
        with:
          command: 'pnpm run prisma:migrate'

      - name: build
        uses: './.github/workflows/excute_pnpm_command.yaml'
        with:
          command: 'pnpm run build'

  run_lint:
    uses: './.github/workflows/excute_pnpm_command.yaml'
    with:
      command: 'pnpm run lint'
