name: 'Run CI'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: 'read'

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - name: migrate
        uses: './.github/workflows/excute_pnpm_command.yaml'
        with:
          command: 'pnpm run prisma:migrate'
      - name: build
        uses: './.github/workflows/excute_pnpm_command.yaml'
        with:
          command: 'pnpm run build'

  run_lint:
    uses: './.github/workflows/excute_pnpm_command.yaml'
    with:
      command: 'pnpm run lint'
